version: "3.8"
networks:
  personal-network:
    external: true
services:
  urlshortener-service:
    build:
      context: ./source/urlshortener
      dockerfile: Dockerfile
      args:
        userID: ${userID}
        groupID: ${groupID}
    volumes:
      - ./:/app/
      - ~/.gradle:/tmp/gradle_user_home
    working_dir: /app/source/urlshortener/
    environment:
      - LIVE_RELOAD=false
    command: [ "sh", "./run.sh" ]
    user: ${userID}:${groupID}
    networks:
      - personal-network
    ports:
      - 5006:5006
      - 8080:8080
    hostname: urlshortener-service
    container_name: urlshortener-service